import "./globals.css";

export const metadata = {
  title: "Chat-Web-App",
  description: "Generated by David",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
